contentColumnType: string
fieldGroup: 8b413b3b-270d-4fdf-b737-1a12054e063c
handle: contactInfo
instructions: ''
name: 'Contact info'
searchable: true
settings:
  contentTable: '{{%stc_contactinfo}}'
  fieldLayout: matrix
  maxRows: ''
  minRows: ''
  propagationMethod: all
  selectionLabel: ''
  staticField: '1'
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
