enableVersioning: true
handle: horoskop
name: Horoskop
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  b595d07a-02d1-48d2-becf-8d8def260287:
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: 'horoskop/{slug}'
type: channel
